# Generated by Django 4.2.7 on 2024-04-29 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_alter_city_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=150, verbose_name='Название модели')),
                ('image', models.ImageField(upload_to='aircraft_images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'самолет',
                'verbose_name_plural': 'самолеты',
                'db_table': 'aircraft',
            },
        ),
        migrations.CreateModel(
            name='airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название аэропорта')),
            ],
            options={
                'verbose_name': 'аэропорт',
                'verbose_name_plural': 'аэропорты',
                'db_table': 'airport',
            },
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'город', 'verbose_name_plural': 'города'},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена маршрута')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_airport', to='routes.airport', verbose_name='Аэропорт вылета')),
                ('destination_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_airport', to='routes.airport', verbose_name='Аэропорт назначения')),
            ],
            options={
                'verbose_name': 'маршрут',
                'verbose_name_plural': 'маршруты',
                'db_table': 'route',
            },
        ),
        migrations.CreateModel(
            name='flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateTimeField(verbose_name='Дата вылета')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.aircraft', verbose_name='Самолет')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.route', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'рейс',
                'verbose_name_plural': 'рейсы',
                'db_table': 'flight',
            },
        ),
        migrations.AddField(
            model_name='airport',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airports', to='routes.city', verbose_name='Город'),
        ),
    ]
