# Generated by Django 4.2.7 on 2024-04-30 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_route_available_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='День недели')),
            ],
        ),
        migrations.RemoveField(
            model_name='route',
            name='available_days',
        ),
        migrations.AlterField(
            model_name='route',
            name='departure_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_routes', to='routes.airport', verbose_name='Аэропорт вылета'),
        ),
        migrations.AlterField(
            model_name='route',
            name='destination_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_routes', to='routes.airport', verbose_name='Аэропорт назначения'),
        ),
        migrations.AddField(
            model_name='route',
            name='available_days',
            field=models.ManyToManyField(to='routes.dayofweek', verbose_name='Дни недели, когда доступен маршрут'),
        ),
    ]
