# Generated by Django 4.2.7 on 2024-05-01 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_dayofweek_remove_route_available_days_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayofweek',
            options={'verbose_name': 'день недели', 'verbose_name_plural': 'дни недели'},
        ),
        migrations.AlterModelTable(
            name='dayofweek',
            table='dayofweek',
        ),
        migrations.CreateModel(
            name='seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10, verbose_name='Номер места')),
                ('is_taken', models.BooleanField(default=False, verbose_name='Занято ли место')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='routes.aircraft', verbose_name='Самолет')),
            ],
            options={
                'verbose_name': 'место',
                'verbose_name_plural': 'места',
                'db_table': 'seat',
                'unique_together': {('aircraft', 'seat_number')},
            },
        ),
        migrations.CreateModel(
            name='cabin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(verbose_name='Номер ряда')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='routes.aircraft', verbose_name='Самолет')),
                ('seats', models.ManyToManyField(related_name='rows', to='routes.seat', verbose_name='Места в ряду')),
            ],
            options={
                'verbose_name': 'ряд',
                'verbose_name_plural': 'ряды',
                'db_table': 'cabin',
                'unique_together': {('aircraft', 'row_number')},
            },
        ),
    ]
