# Generated by Django 4.2.7 on 2024-05-04 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_flight_arrival_date_flight_flight_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='cabin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.cabin', verbose_name='Схема салона'),
        ),
    ]
