# Generated by Django 4.2.7 on 2024-05-24 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0009_adultpassenger_childpassenger_pet_passenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerSeatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.flight', verbose_name='Рейс')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.passenger', verbose_name='Пассажир')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.cabin', verbose_name='Ряд')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.seat', verbose_name='Место')),
            ],
            options={
                'verbose_name': 'назначение места пассажиру',
                'verbose_name_plural': 'назначения мест пассажирам',
                'db_table': 'passenger_seat_assignment',
            },
        ),
    ]
