# Generated by Django 4.2.7 on 2024-05-25 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routes', '0010_passengerseatassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passengerseatassignment',
            options={'verbose_name': 'назначение места пользователю', 'verbose_name_plural': 'назначения мест пользователям'},
        ),
        migrations.RemoveField(
            model_name='passengerseatassignment',
            name='passenger',
        ),
        migrations.AddField(
            model_name='passengerseatassignment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
