# Generated by Django 4.2.7 on 2024-05-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0011_alter_passengerseatassignment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='birth_certificate_number',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='birth_certificate_series',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='species',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='vaccination_certificate_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='vet_passport_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
