# Generated by Django 4.2.7 on 2024-05-29 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routes', '0012_passenger_birth_certificate_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.flight', verbose_name='Рейс')),
                ('passengers', models.ManyToManyField(to='routes.passenger', verbose_name='Пассажиры')),
                ('seat_assignments', models.ManyToManyField(to='routes.passengerseatassignment', verbose_name='Назначенные места')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'букинг',
                'verbose_name_plural': 'букинги',
                'db_table': 'booking',
            },
        ),
    ]
