# Generated by Django 4.2.7 on 2024-05-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0013_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultpassenger',
            name='seat',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='childpassenger',
            name='seat',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='seat',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='seat',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
