# Generated by Django 4.2.7 on 2024-05-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0015_passenger_patronymic'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerseatassignment',
            name='passengers',
            field=models.ManyToManyField(to='routes.passenger', verbose_name='Пассажиры'),
        ),
    ]
