# Generated by Django 4.2.7 on 2024-05-31 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0016_passengerseatassignment_passengers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengerseatassignment',
            name='passengers',
        ),
        migrations.AddField(
            model_name='passengerseatassignment',
            name='passenger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='routes.passenger', verbose_name='Пассажир'),
            preserve_default=False,
        ),
    ]
