# Generated by Django 4.2.7 on 2024-06-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0017_remove_passengerseatassignment_passengers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR-код'),
        ),
    ]
